install: smplpkg
	php smplpkg/smplpkg.php install test2
smplpkg:
	git clone git@github.com:hsk/smplpkg.git
list:
	php smplpkg/smplpkg.php list
usage:
	php smplpkg/smplpkg.php usage
clean:
	rm -rf test1 test2 smplpkg
run:
	php test.php
